kind: Service
apiVersion: v1
metadata:
  name: hello-cloud
  labels:
    app: hello-cloud
spec:
  selector:
    app: hello-cloud
  ports:
    - port: 8080
      name: http
  type: NodePort
---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: hello-cloud
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-cloud
        version: v1
    spec:
      containers:
      - name: hello-cloud
        image: docker.sebastian-daschner.com/hello-cloud:1
        imagePullPolicy: Always
      imagePullSecrets:
      - name: regsecret
      restartPolicy: Always
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: hello-cloud
spec:
  rules:
    - host: kubernetes.local
      http:
        paths:
        - path: /hello-cloud
          backend:
            serviceName: hello-cloud
            servicePort: 8080
---