kind: Service
apiVersion: v1
metadata:
  name: hello-cloud
  labels:
    app: hello-cloud
spec:
  selector:
    app: hello-cloud
  ports:
    - port: 9080
      name: http
  type: NodePort
---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: hello-cloud
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-cloud
        version: v1
    spec:
      containers:
      - name: hello-cloud
        image: docker.sebastian-daschner.com/hello-cloud:1
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 9080
        readinessProbe:
          httpGet:
            path: /hello-cloud/resources/health
            port: 9080
      imagePullSecrets:
      - name: regsecret
      restartPolicy: Always
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: hello-cloud
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - http:
        paths:
        - path: /hello-cloud
          backend:
            serviceName: hello-cloud
            servicePort: 9080
---
